@server = http://localhost:4004

### GET Book
GET {{server}}/browse/Book HTTP/1.1

### GET Author
GET {{server}}/browse/Author HTTP/1.1

### GET Character
GET {{server}}/browse/Character HTTP/1.1

### Post Author
POST {{server}}/browse/Author 
Content-Type: application/json

{
	"firstName": "Terence Dean",
	"secondName": "Brooks",
	"birthDate": "1944-01-08",
	"placeBirth": "Sterling",
    "nationality" : "United States"
}

### Post Character
PATCH  {{server}}/browse/Book(067a08e9-d7b4-4486-9094-bc81e96ea89c) HTTP/1.1
content-type: application/json

{
    "author"  :  {
		"ID": "28566f06-416d-40f0-b4f3-4ef566aa1427",
		"firstName": "James",
		"secondName": "Luceno",
		"birthDate": "1947-01-01",
		"placeBirth": "Bermuda",
		"age": 76,
		"nationality": "United States",
		"books_ID": "067a08e9-d7b4-4486-9094-bc81e96ea89c"
	}
}

### POST Book
PATCH  {{server}}/browse/Book(db7e31c7-7e27-4fdc-ac42-d0ba9b0b7ecd) HTTP/1.1
Content-Type: application/json

{
	"author_ID" : "28566f06-416d-40f0-b4f3-4ef566aa1427"
}

###
GET {{server}}/browse/getTheOldestAuthor()

###
GET {{server}}/browse/getTheYoungestAuthor()

###
GET {{server}}/browse/timeBetweenTwoDates(firstDate='15BBY',secondDate='16BBY')

###
GET {{server}}/browse/timeBetweenTwoDates(firstDate='15BBY',secondDate='16ABY')

###
GET {{server}}/browse/convert2ImperialCredit(currType='Wupiup',quantity=10)

###
GET {{server}}/browse/getNoBook()

###
GET {{server}}/browse/getNoAuthor()

###
GET {{server}}/browse/getPDFFile()

###
GET https://swapi.dev/api/starships/9/